linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - lll
    - gci
    - misspell
    - whitespace
    - tparallel

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(backend)
      - blank
      - dot
